spring:
  datasource:
    url: "jdbc:mariadb://localhost:10036/covid-ma-dose"
    username: "covidmadose"
    password: "covidmadose"
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      max-active: 2
      max-idle: 2
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
server:
  port: 8082
covidmadose:
  front: "http://localhost:8081"
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor: DEBUG